trigger:
- main
- rel/*

pr:
- main
- rel/*


stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest

    variables: 
      BuildConfiguration: Release
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
    - task: UseDotNet@2
      displayName: Install .NET 6
      inputs:
        version: 6.x

    - task: UseDotNet@2
      displayName: Install .NET 8
      inputs:
        version: 8.x

    - task: DotNetCoreCLI@2  
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . nbgv
      displayName: Install NBGV tool

    - script: nbgv cloud
      displayName: Set Version

    - task: VSBuild@1
      inputs:    
        solution: .\Zeroconf\Zeroconf.csproj
        configuration: $(BuildConfiguration)
        msbuildArgs: '/restore /m /t:Pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\Packages'        
      displayName: Build / Pack

    - publish: $(Build.ArtifactStagingDirectory)\Packages
      displayName: Publish build packages
      artifact: BuildPackages

- stage: CodeSign
  condition: and(succeeded('Build'), not(eq(variables['build.reason'], 'PullRequest')))
  dependsOn: Build
  variables: 
    - group: Trusted Signing Config
  jobs:
  - job: CodeSign
    displayName: Code Signing
    pool:
      vmImage: windows-latest    

    steps: 

    - download: current
      artifact: BuildPackages

    - task: UseDotNet@2
      displayName: 'Use .NET SDK 9.x'
      inputs:
        version: 9.x

    # Install the code signing tool
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . --prerelease sign
      displayName: Install Sign CLI tool

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure - Claire Novotny LLC'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          .\sign code trusted-signing `
          "**/*.nupkg" `
          --base-directory "$(Pipeline.Workspace)\BuildPackages" `
          --publisher-name "Claire Novotny LLC" `
          --description "Zeroconf" `
          --description-url "https://github.com/novotnyllc/Zeroconf" `
          --trusted-signing-endpoint "$(TrustedSigningEndpoint)" `
          --trusted-signing-account "$(TrustedSigningAccount)" `
          --trusted-signing-certificate-profile "$(TrustedSigningCertificateProfile)"
      displayName: Sign artifacts

    - publish: $(Pipeline.Workspace)/BuildPackages
      displayName: Publish Signed Packages
      artifact: SignedPackages
